# Generated by Django 6.0.3 on 2026-07-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='modified_by',
            new_name='updated_by',
        ),
        migrations.RemoveField(
            model_name='article',
            name='external_link',
        ),
    ]
