# Generated by Django 6.0.3 on 2026-07-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_data', '0002_rename_modified_by_article_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
