# Generated by Django 6.0.3 on 2026-08-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_data', '0005_alter_article_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
